services:
  backend:
    image: alokvernekar/evg-backend:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    env_file: .env
    volumes:
      - app_data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: alokvernekar/evg-frontend:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  app_data:
